import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.HashSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seedlessmango98
 */
public class CoffeeOrder extends javax.swing.JFrame {
    
    Products[] coffee;
    int[] stock_f1, stock_f2, stock_f3, stock_f4, stock_f5;
    int[] client_order_list;
    String[] client_order;
    String[] data_reference;
    String[] user_reference;
    String receipt_log_path;
    Cashier[] admin;
    Cashier currentUser;
    /**
     * Creates new form CoffeeOrder
     */
    public CoffeeOrder() {
        this.user_reference = new String[] {
            "txt/cashier_gab.txt",
            "txt/cashier_begz.txt"
        };
        this.data_reference = new String[] {
            "txt/cafè_americano.txt",
            "txt/cappuccino.txt",
            "txt/cafè_latte.txt",
            "txt/caramel_latte.txt",
            "txt/cafè_mocha.txt"
        };
        this.coffee = new Products[] {
            new Products(this.data_reference[0]),
            new Products(this.data_reference[1]),
            new Products(this.data_reference[2]),
            new Products(this.data_reference[3]),
            new Products(this.data_reference[4])
        };
        this.admin = new Cashier[] {
            new Cashier(this.user_reference[0]),
            new Cashier(this.user_reference[1])
        };
        this.currentUser = null;
        this.stock_f1 = new int[]{30, 30};
        this.stock_f2 = new int[]{30, 30};
        this.stock_f3 = new int[]{30, 30};
        this.stock_f4 = new int[]{30, 30};
        this.stock_f5 = new int[]{30, 30};
        this.client_order_list = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        this.client_order = new String[]{};
        this.receipt_log_path = "txt/log_receipt.txt";
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        pnl_client = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_client_coffee = new javax.swing.JPanel();
        btn_sel_c1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_sel_c2 = new javax.swing.JButton();
        btn_sel_c3 = new javax.swing.JButton();
        btn_buytall_c1 = new javax.swing.JButton();
        btn_buygrande_c1 = new javax.swing.JButton();
        btn_buytall_c2 = new javax.swing.JButton();
        btn_buygrande_c2 = new javax.swing.JButton();
        btn_buytall_c3 = new javax.swing.JButton();
        btn_buygrande_c3 = new javax.swing.JButton();
        btn_sel_c4 = new javax.swing.JButton();
        btn_buytall_c4 = new javax.swing.JButton();
        btn_buygrande_c4 = new javax.swing.JButton();
        btn_sel_c5 = new javax.swing.JButton();
        btn_buytall_c5 = new javax.swing.JButton();
        btn_buygrande_c5 = new javax.swing.JButton();
        lbl_client_img = new javax.swing.JLabel();
        pnl_client_frappe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_sel_f1 = new javax.swing.JButton();
        btn_buygrande_f1 = new javax.swing.JButton();
        btn_buyproject_f1 = new javax.swing.JButton();
        btn_sel_f2 = new javax.swing.JButton();
        btn_buygrande_f2 = new javax.swing.JButton();
        btn_buyproject_f2 = new javax.swing.JButton();
        btn_sel_f3 = new javax.swing.JButton();
        btn_buygrande_f3 = new javax.swing.JButton();
        btn_buyproject_f3 = new javax.swing.JButton();
        btn_sel_f4 = new javax.swing.JButton();
        btn_buygrande_f4 = new javax.swing.JButton();
        btn_buyproject_f4 = new javax.swing.JButton();
        btn_sel_f5 = new javax.swing.JButton();
        btn_buygrande_f5 = new javax.swing.JButton();
        btn_buyproject_f5 = new javax.swing.JButton();
        pnl_client_receipt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_client_receipt = new javax.swing.JTable();
        btn_client_confirm = new javax.swing.JButton();
        btn_client_cancel = new javax.swing.JButton();
        btn_adminLogin = new javax.swing.JButton();
        pnl_admin = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnl_admin_main = new javax.swing.JPanel();
        btn_admin_logout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pwd_old = new javax.swing.JPasswordField();
        pwd_new = new javax.swing.JPasswordField();
        pwd_confirm = new javax.swing.JPasswordField();
        btn_admin_pwdChange = new javax.swing.JButton();
        btn_admin_confirmPwd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(848, 480));
        setMinimumSize(new java.awt.Dimension(848, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(848, 480));

        pnl_main.setBackground(new java.awt.Color(0, 0, 0));
        pnl_main.setLayout(new java.awt.CardLayout());

        pnl_client.setBackground(new java.awt.Color(0, 0, 0));
        pnl_client.setPreferredSize(new java.awt.Dimension(828, 480));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N

        pnl_client_coffee.setBackground(new java.awt.Color(0, 0, 0));

        btn_sel_c1.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_c1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_c1.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_c1.setText("Cafè Americano");
        btn_sel_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_c1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tall");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Grande");

        btn_sel_c2.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_c2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_c2.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_c2.setText("Cappuccino");
        btn_sel_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_c2ActionPerformed(evt);
            }
        });

        btn_sel_c3.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_c3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_c3.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_c3.setText("Cafè Latte");
        btn_sel_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_c3ActionPerformed(evt);
            }
        });

        btn_buytall_c1.setBackground(new java.awt.Color(0, 0, 0));
        btn_buytall_c1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buytall_c1.setForeground(new java.awt.Color(255, 255, 255));
        btn_buytall_c1.setText("120");
        btn_buytall_c1.setEnabled(false);
        btn_buytall_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buytall_c1ActionPerformed(evt);
            }
        });

        btn_buygrande_c1.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_c1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_c1.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_c1.setText("135");
        btn_buygrande_c1.setEnabled(false);
        btn_buygrande_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buygrande_c1ActionPerformed(evt);
            }
        });

        btn_buytall_c2.setBackground(new java.awt.Color(0, 0, 0));
        btn_buytall_c2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buytall_c2.setForeground(new java.awt.Color(255, 255, 255));
        btn_buytall_c2.setText("130");
        btn_buytall_c2.setEnabled(false);
        btn_buytall_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buytall_c2ActionPerformed(evt);
            }
        });

        btn_buygrande_c2.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_c2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_c2.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_c2.setText("145");
        btn_buygrande_c2.setEnabled(false);
        btn_buygrande_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buygrande_c2ActionPerformed(evt);
            }
        });

        btn_buytall_c3.setBackground(new java.awt.Color(0, 0, 0));
        btn_buytall_c3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buytall_c3.setForeground(new java.awt.Color(255, 255, 255));
        btn_buytall_c3.setText("130");
        btn_buytall_c3.setEnabled(false);
        btn_buytall_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buytall_c3ActionPerformed(evt);
            }
        });

        btn_buygrande_c3.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_c3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_c3.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_c3.setText("145");
        btn_buygrande_c3.setEnabled(false);
        btn_buygrande_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buygrande_c3ActionPerformed(evt);
            }
        });

        btn_sel_c4.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_c4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_c4.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_c4.setText("Caramel Latte");
        btn_sel_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_c4ActionPerformed(evt);
            }
        });

        btn_buytall_c4.setBackground(new java.awt.Color(0, 0, 0));
        btn_buytall_c4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buytall_c4.setForeground(new java.awt.Color(255, 255, 255));
        btn_buytall_c4.setText("155");
        btn_buytall_c4.setEnabled(false);
        btn_buytall_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buytall_c4ActionPerformed(evt);
            }
        });

        btn_buygrande_c4.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_c4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_c4.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_c4.setText("170");
        btn_buygrande_c4.setEnabled(false);
        btn_buygrande_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buygrande_c4ActionPerformed(evt);
            }
        });

        btn_sel_c5.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_c5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_c5.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_c5.setText("Cafè Mocha");
        btn_sel_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_c5ActionPerformed(evt);
            }
        });

        btn_buytall_c5.setBackground(new java.awt.Color(0, 0, 0));
        btn_buytall_c5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buytall_c5.setForeground(new java.awt.Color(255, 255, 255));
        btn_buytall_c5.setText("145");
        btn_buytall_c5.setEnabled(false);
        btn_buytall_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buytall_c5ActionPerformed(evt);
            }
        });

        btn_buygrande_c5.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_c5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_c5.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_c5.setText("160");
        btn_buygrande_c5.setEnabled(false);
        btn_buygrande_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buygrande_c5ActionPerformed(evt);
            }
        });

        lbl_client_img.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl_client_coffeeLayout = new javax.swing.GroupLayout(pnl_client_coffee);
        pnl_client_coffee.setLayout(pnl_client_coffeeLayout);
        pnl_client_coffeeLayout.setHorizontalGroup(
            pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                        .addComponent(lbl_client_img, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                        .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                                .addComponent(btn_sel_c5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_buytall_c5))
                            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                                .addComponent(btn_sel_c1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(btn_buytall_c1))
                            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                                .addComponent(btn_sel_c2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_buytall_c2))
                            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                                .addComponent(btn_sel_c3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_buytall_c3))
                            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                                .addComponent(btn_sel_c4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_buytall_c4)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(btn_buygrande_c1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(btn_buygrande_c2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(btn_buygrande_c3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(btn_buygrande_c4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btn_buygrande_c5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnl_client_coffeeLayout.setVerticalGroup(
            pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_client_coffeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_c1)
                    .addComponent(btn_buytall_c1)
                    .addComponent(btn_buygrande_c1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_c2)
                    .addComponent(btn_buytall_c2)
                    .addComponent(btn_buygrande_c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_c3)
                    .addComponent(btn_buytall_c3)
                    .addComponent(btn_buygrande_c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_c4)
                    .addComponent(btn_buytall_c4)
                    .addComponent(btn_buygrande_c4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_c5)
                    .addComponent(btn_buytall_c5)
                    .addComponent(btn_buygrande_c5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_client_img, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Coffee", pnl_client_coffee);

        pnl_client_frappe.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grande");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Project");

        btn_sel_f1.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_f1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_f1.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_f1.setText("Dark Chocolate");
        btn_sel_f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_f1ActionPerformed(evt);
            }
        });

        btn_buygrande_f1.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_f1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_f1.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_f1.setText("160");
        btn_buygrande_f1.setEnabled(false);

        btn_buyproject_f1.setBackground(new java.awt.Color(0, 0, 0));
        btn_buyproject_f1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buyproject_f1.setForeground(new java.awt.Color(255, 255, 255));
        btn_buyproject_f1.setText("175");
        btn_buyproject_f1.setEnabled(false);

        btn_sel_f2.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_f2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_f2.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_f2.setText("Vanilla Macadamia");
        btn_sel_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_f2ActionPerformed(evt);
            }
        });

        btn_buygrande_f2.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_f2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_f2.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_f2.setText("160");
        btn_buygrande_f2.setEnabled(false);

        btn_buyproject_f2.setBackground(new java.awt.Color(0, 0, 0));
        btn_buyproject_f2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buyproject_f2.setForeground(new java.awt.Color(255, 255, 255));
        btn_buyproject_f2.setText("175");
        btn_buyproject_f2.setEnabled(false);

        btn_sel_f3.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_f3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_f3.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_f3.setText("Chocolate Cookie");
        btn_sel_f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_f3ActionPerformed(evt);
            }
        });

        btn_buygrande_f3.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_f3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_f3.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_f3.setText("180");
        btn_buygrande_f3.setEnabled(false);

        btn_buyproject_f3.setBackground(new java.awt.Color(0, 0, 0));
        btn_buyproject_f3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buyproject_f3.setForeground(new java.awt.Color(255, 255, 255));
        btn_buyproject_f3.setText("195");
        btn_buyproject_f3.setEnabled(false);

        btn_sel_f4.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_f4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_f4.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_f4.setText("Caramel Vanilla");
        btn_sel_f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_f4ActionPerformed(evt);
            }
        });

        btn_buygrande_f4.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_f4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_f4.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_f4.setText("165");
        btn_buygrande_f4.setEnabled(false);

        btn_buyproject_f4.setBackground(new java.awt.Color(0, 0, 0));
        btn_buyproject_f4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buyproject_f4.setForeground(new java.awt.Color(255, 255, 255));
        btn_buyproject_f4.setText("180");
        btn_buyproject_f4.setEnabled(false);

        btn_sel_f5.setBackground(new java.awt.Color(0, 0, 0));
        btn_sel_f5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sel_f5.setForeground(new java.awt.Color(255, 255, 255));
        btn_sel_f5.setText("Strawberry Vanilla");
        btn_sel_f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sel_f5ActionPerformed(evt);
            }
        });

        btn_buygrande_f5.setBackground(new java.awt.Color(0, 0, 0));
        btn_buygrande_f5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buygrande_f5.setForeground(new java.awt.Color(255, 255, 255));
        btn_buygrande_f5.setText("180");
        btn_buygrande_f5.setEnabled(false);

        btn_buyproject_f5.setBackground(new java.awt.Color(0, 0, 0));
        btn_buyproject_f5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_buyproject_f5.setForeground(new java.awt.Color(255, 255, 255));
        btn_buyproject_f5.setText("195");
        btn_buyproject_f5.setEnabled(false);

        javax.swing.GroupLayout pnl_client_frappeLayout = new javax.swing.GroupLayout(pnl_client_frappe);
        pnl_client_frappe.setLayout(pnl_client_frappeLayout);
        pnl_client_frappeLayout.setHorizontalGroup(
            pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_client_frappeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_client_frappeLayout.createSequentialGroup()
                        .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_sel_f1)
                            .addComponent(btn_sel_f2)
                            .addComponent(btn_sel_f3)
                            .addComponent(btn_sel_f4)
                            .addComponent(btn_sel_f5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buygrande_f1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buygrande_f2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buygrande_f3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buygrande_f4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buygrande_f5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnl_client_frappeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_buyproject_f1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_buyproject_f2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_buyproject_f3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_buyproject_f4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btn_buyproject_f5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_client_frappeLayout.setVerticalGroup(
            pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_client_frappeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_f1)
                    .addComponent(btn_buygrande_f1)
                    .addComponent(btn_buyproject_f1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_f2)
                    .addComponent(btn_buygrande_f2)
                    .addComponent(btn_buyproject_f2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_f3)
                    .addComponent(btn_buygrande_f3)
                    .addComponent(btn_buyproject_f3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_f4)
                    .addComponent(btn_buygrande_f4)
                    .addComponent(btn_buyproject_f4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_client_frappeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sel_f5)
                    .addComponent(btn_buygrande_f5)
                    .addComponent(btn_buyproject_f5))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Frappe", pnl_client_frappe);

        pnl_client_receipt.setBackground(new java.awt.Color(0, 0, 0));
        pnl_client_receipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_client_receipt.setBackground(new java.awt.Color(0, 0, 0));
        tbl_client_receipt.setForeground(new java.awt.Color(255, 255, 255));
        tbl_client_receipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Qty", "Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_client_receipt);

        btn_client_confirm.setBackground(new java.awt.Color(0, 0, 0));
        btn_client_confirm.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_client_confirm.setForeground(new java.awt.Color(255, 255, 255));
        btn_client_confirm.setText("Confirm Order");
        btn_client_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_client_confirmActionPerformed(evt);
            }
        });

        btn_client_cancel.setBackground(new java.awt.Color(0, 0, 0));
        btn_client_cancel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_client_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_client_cancel.setText("Cancel Order");
        btn_client_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_client_cancelActionPerformed(evt);
            }
        });

        btn_adminLogin.setBackground(new java.awt.Color(0, 0, 0));
        btn_adminLogin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_adminLogin.setForeground(new java.awt.Color(255, 255, 255));
        btn_adminLogin.setText("Login Admin");
        btn_adminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_client_receiptLayout = new javax.swing.GroupLayout(pnl_client_receipt);
        pnl_client_receipt.setLayout(pnl_client_receiptLayout);
        pnl_client_receiptLayout.setHorizontalGroup(
            pnl_client_receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_client_receiptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_client_receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_client_confirm, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(btn_client_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_adminLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_client_receiptLayout.setVerticalGroup(
            pnl_client_receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_client_receiptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_client_confirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_client_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adminLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_clientLayout = new javax.swing.GroupLayout(pnl_client);
        pnl_client.setLayout(pnl_clientLayout);
        pnl_clientLayout.setHorizontalGroup(
            pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_client_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_clientLayout.setVerticalGroup(
            pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnl_client_receipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_main.add(pnl_client, "card2");

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N

        pnl_admin_main.setBackground(new java.awt.Color(0, 0, 0));
        pnl_admin_main.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        btn_admin_logout.setBackground(new java.awt.Color(0, 0, 0));
        btn_admin_logout.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn_admin_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_admin_logout.setText("Logout");
        btn_admin_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_logoutActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Old Password:");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Password:");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password:");

        pwd_old.setEditable(false);
        pwd_old.setBackground(new java.awt.Color(0, 0, 0));
        pwd_old.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pwd_old.setForeground(new java.awt.Color(255, 255, 255));

        pwd_new.setEditable(false);
        pwd_new.setBackground(new java.awt.Color(0, 0, 0));
        pwd_new.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pwd_new.setForeground(new java.awt.Color(255, 255, 255));

        pwd_confirm.setEditable(false);
        pwd_confirm.setBackground(new java.awt.Color(0, 0, 0));
        pwd_confirm.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pwd_confirm.setForeground(new java.awt.Color(255, 255, 255));

        btn_admin_pwdChange.setBackground(new java.awt.Color(0, 0, 0));
        btn_admin_pwdChange.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_admin_pwdChange.setForeground(new java.awt.Color(255, 255, 255));
        btn_admin_pwdChange.setText("Change Password");
        btn_admin_pwdChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_pwdChangeActionPerformed(evt);
            }
        });

        btn_admin_confirmPwd.setBackground(new java.awt.Color(0, 0, 0));
        btn_admin_confirmPwd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_admin_confirmPwd.setForeground(new java.awt.Color(255, 255, 255));
        btn_admin_confirmPwd.setText("Confirm Change");
        btn_admin_confirmPwd.setEnabled(false);
        btn_admin_confirmPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_confirmPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_admin_mainLayout = new javax.swing.GroupLayout(pnl_admin_main);
        pnl_admin_main.setLayout(pnl_admin_mainLayout);
        pnl_admin_mainLayout.setHorizontalGroup(
            pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_admin_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_admin_mainLayout.createSequentialGroup()
                        .addComponent(btn_admin_pwdChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                        .addComponent(btn_admin_confirmPwd))
                    .addGroup(pnl_admin_mainLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwd_old, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_admin_mainLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwd_new, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_admin_mainLayout.createSequentialGroup()
                        .addComponent(btn_admin_logout)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_admin_mainLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwd_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_admin_mainLayout.setVerticalGroup(
            pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_admin_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pwd_old, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pwd_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pwd_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_admin_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_admin_pwdChange)
                    .addComponent(btn_admin_confirmPwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btn_admin_logout)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Main", pnl_admin_main);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Inventory", jPanel1);

        javax.swing.GroupLayout pnl_adminLayout = new javax.swing.GroupLayout(pnl_admin);
        pnl_admin.setLayout(pnl_adminLayout);
        pnl_adminLayout.setHorizontalGroup(
            pnl_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        pnl_adminLayout.setVerticalGroup(
            pnl_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pnl_main.add(pnl_admin, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sel_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_c1ActionPerformed
        // TODO add your handling code here:
        btn_buytall_c1.setText(Integer.toString(this.coffee[0].getPrice(0)));
        btn_buygrande_c1.setText(Integer.toString(this.coffee[0].getPrice(1)));
        if(btn_buytall_c1.isEnabled()){
            btn_buytall_c1.setEnabled(false);
            btn_buygrande_c1.setEnabled(false);
            lbl_client_img.setIcon(null);
        }else{
            BufferedImage img;
            try{
                img = ImageIO.read(new File(this.coffee[0].getImgPath()));
                Image dimg = img.getScaledInstance(lbl_client_img.getWidth(),
                        lbl_client_img.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                lbl_client_img.setIcon(imageIcon);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error:\n" + e);
            }
            btn_buytall_c1.setEnabled(true);
            btn_buygrande_c1.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_c1ActionPerformed

    private void btn_sel_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_c2ActionPerformed
        // TODO add your handling code here:
        btn_buytall_c2.setText(Integer.toString(this.coffee[1].getPrice(0)));
        btn_buygrande_c2.setText(Integer.toString(this.coffee[1].getPrice(1)));
        if(btn_buytall_c2.isEnabled()){
            btn_buytall_c2.setEnabled(false);
            btn_buygrande_c2.setEnabled(false);
            lbl_client_img.setIcon(null);
        }else{
            BufferedImage img;
            try{
                img = ImageIO.read(new File(this.coffee[1].getImgPath()));
                Image dimg = img.getScaledInstance(lbl_client_img.getWidth(),
                        lbl_client_img.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                lbl_client_img.setIcon(imageIcon);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error:\n" + e);
            }
            btn_buytall_c2.setEnabled(true);
            btn_buygrande_c2.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_c2ActionPerformed

    private void btn_sel_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_c3ActionPerformed
        // TODO add your handling code here:
        btn_buytall_c3.setText(Integer.toString(this.coffee[2].getPrice(0)));
        btn_buygrande_c3.setText(Integer.toString(this.coffee[2].getPrice(1)));
        if(btn_buytall_c3.isEnabled()){
            btn_buytall_c3.setEnabled(false);
            btn_buygrande_c3.setEnabled(false);
            lbl_client_img.setIcon(null);
        }else{
            BufferedImage img;
            try{
                img = ImageIO.read(new File(this.coffee[2].getImgPath()));
                Image dimg = img.getScaledInstance(lbl_client_img.getWidth(),
                        lbl_client_img.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                lbl_client_img.setIcon(imageIcon);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error:\n" + e);
            }
            btn_buytall_c3.setEnabled(true);
            btn_buygrande_c3.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_c3ActionPerformed

    private void btn_sel_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_c4ActionPerformed
        // TODO add your handling code here:
        btn_buytall_c4.setText(Integer.toString(this.coffee[3].getPrice(0)));
        btn_buygrande_c4.setText(Integer.toString(this.coffee[3].getPrice(1)));
        if(btn_buytall_c4.isEnabled()){
            btn_buytall_c4.setEnabled(false);
            btn_buygrande_c4.setEnabled(false);
            lbl_client_img.setIcon(null);
        }else{
            BufferedImage img;
            try{
                img = ImageIO.read(new File(this.coffee[3].getImgPath()));
                Image dimg = img.getScaledInstance(lbl_client_img.getWidth(),
                        lbl_client_img.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                lbl_client_img.setIcon(imageIcon);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error:\n" + e);
            }
            btn_buytall_c4.setEnabled(true);
            btn_buygrande_c4.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_c4ActionPerformed

    private void btn_sel_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_c5ActionPerformed
        // TODO add your handling code here:
        btn_buytall_c5.setText(Integer.toString(this.coffee[4].getPrice(0)));
        btn_buygrande_c5.setText(Integer.toString(this.coffee[4].getPrice(1)));
        if(btn_buytall_c5.isEnabled()){
            btn_buytall_c5.setEnabled(false);
            btn_buygrande_c5.setEnabled(false);
            lbl_client_img.setIcon(null);
        }else{
            BufferedImage img;
            try{
                img = ImageIO.read(new File(this.coffee[4].getImgPath()));
                Image dimg = img.getScaledInstance(lbl_client_img.getWidth(),
                        lbl_client_img.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                lbl_client_img.setIcon(imageIcon);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error:\n" + e);
            }
            btn_buytall_c5.setEnabled(true);
            btn_buygrande_c5.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_c5ActionPerformed

    private void btn_sel_f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_f1ActionPerformed
        // TODO add your handling code here:
        if(btn_buygrande_f1.isEnabled()){
            btn_buygrande_f1.setEnabled(false);
            btn_buyproject_f1.setEnabled(false);
        }else{
            btn_buygrande_f1.setEnabled(true);
            btn_buyproject_f1.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_f1ActionPerformed

    private void btn_sel_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_f2ActionPerformed
        // TODO add your handling code here:
        if(btn_buygrande_f2.isEnabled()){
            btn_buygrande_f2.setEnabled(false);
            btn_buyproject_f2.setEnabled(false);
        }else{
            btn_buygrande_f2.setEnabled(true);
            btn_buyproject_f2.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_f2ActionPerformed

    private void btn_sel_f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_f3ActionPerformed
        // TODO add your handling code here:
        if(btn_buygrande_f3.isEnabled()){
            btn_buygrande_f3.setEnabled(false);
            btn_buyproject_f3.setEnabled(false);
        }else{
            btn_buygrande_f3.setEnabled(true);
            btn_buyproject_f3.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_f3ActionPerformed

    private void btn_sel_f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_f4ActionPerformed
        // TODO add your handling code here
        if(btn_buygrande_f4.isEnabled()){
            btn_buygrande_f4.setEnabled(false);
            btn_buyproject_f4.setEnabled(false);
        }else{
            btn_buygrande_f4.setEnabled(true);
            btn_buyproject_f4.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_f4ActionPerformed

    private void btn_sel_f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sel_f5ActionPerformed
        // TODO add your handling code here:
        if(btn_buygrande_f5.isEnabled()){
            btn_buygrande_f5.setEnabled(false);
            btn_buyproject_f5.setEnabled(false);
        }else{
            btn_buygrande_f5.setEnabled(true);
            btn_buyproject_f5.setEnabled(true);
        }
    }//GEN-LAST:event_btn_sel_f5ActionPerformed

    private void btn_buytall_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buytall_c1ActionPerformed
        // TODO add your handling code here:
//        if(stock_c[0][0]!=0){
        if(coffee[0].getQuantity(0)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Tall Cafè Americano?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c1.setEnabled(false);
                btn_buygrande_c1.setEnabled(false);
                this.client_order_list[0]++;
                this.refreshReceipt();
                coffee[0].setQuantity(0,
                        coffee[0].getQuantity(0) - this.client_order_list[0]);
            }
        }
        btn_buytall_c1.setEnabled(false);
        btn_buygrande_c1.setEnabled(false);
    }//GEN-LAST:event_btn_buytall_c1ActionPerformed

    private void btn_buygrande_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buygrande_c1ActionPerformed
        // TODO add your handling code here:
        if(coffee[0].getQuantity(1)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Grande Cafè Americano?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c1.setEnabled(false);
                btn_buygrande_c1.setEnabled(false);
                this.client_order_list[1]++;
                this.refreshReceipt();
                coffee[0].setQuantity(1,
                        coffee[0].getQuantity(1) - this.client_order_list[1]);
            }
        }
        btn_buytall_c1.setEnabled(false);
        btn_buygrande_c1.setEnabled(false);
    }//GEN-LAST:event_btn_buygrande_c1ActionPerformed

    private void btn_buytall_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buytall_c2ActionPerformed
        // TODO add your handling code here:
        if(coffee[1].getQuantity(0)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Tall Cappuccino?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c2.setEnabled(false);
                btn_buygrande_c2.setEnabled(false);
                this.client_order_list[2]++;
                this.refreshReceipt();
                coffee[1].setQuantity(0,
                        coffee[1].getQuantity(0) - this.client_order_list[2]);
            }
        }
        btn_buytall_c2.setEnabled(false);
        btn_buygrande_c2.setEnabled(false);
    }//GEN-LAST:event_btn_buytall_c2ActionPerformed

    private void btn_buygrande_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buygrande_c2ActionPerformed
        // TODO add your handling code here:
        if(coffee[1].getQuantity(1)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Grande Cappuccino?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c2.setEnabled(false);
                btn_buygrande_c2.setEnabled(false);
                this.client_order_list[3]++;
                this.refreshReceipt();
                coffee[1].setQuantity(1,
                        coffee[1].getQuantity(1) - this.client_order_list[3]);
            }
        }
        btn_buytall_c2.setEnabled(false);
        btn_buygrande_c2.setEnabled(false);
    }//GEN-LAST:event_btn_buygrande_c2ActionPerformed

    private void btn_buytall_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buytall_c3ActionPerformed
        // TODO add your handling code here:
        if(coffee[2].getQuantity(0)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Tall Cafè Latte?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c3.setEnabled(false);
                btn_buygrande_c3.setEnabled(false);
                this.client_order_list[4]++;
                this.refreshReceipt();
                coffee[2].setQuantity(0,
                        coffee[2].getQuantity(0) - this.client_order_list[4]);
            }
        }
        btn_buytall_c3.setEnabled(false);
        btn_buygrande_c3.setEnabled(false);
    }//GEN-LAST:event_btn_buytall_c3ActionPerformed

    private void btn_buygrande_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buygrande_c3ActionPerformed
        // TODO add your handling code here:
        if(coffee[2].getQuantity(1)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Grande Cafè Latte?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c3.setEnabled(false);
                btn_buygrande_c3.setEnabled(false);
                this.client_order_list[5]++;
                this.refreshReceipt();
                coffee[2].setQuantity(1,
                        coffee[2].getQuantity(1) - this.client_order_list[5]);
            }
        }
        btn_buytall_c3.setEnabled(false);
        btn_buygrande_c3.setEnabled(false);
    }//GEN-LAST:event_btn_buygrande_c3ActionPerformed

    private void btn_buytall_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buytall_c4ActionPerformed
        // TODO add your handling code here:
        if(coffee[3].getQuantity(0)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Tall Caramel Latte?","Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c4.setEnabled(false);
                btn_buygrande_c4.setEnabled(false);
                this.client_order_list[6]++;
                this.refreshReceipt();
                coffee[3].setQuantity(0,
                        coffee[3].getQuantity(0) - this.client_order_list[6]);
            }
        }
        btn_buytall_c4.setEnabled(false);
        btn_buygrande_c4.setEnabled(false);
    }//GEN-LAST:event_btn_buytall_c4ActionPerformed

    private void btn_buygrande_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buygrande_c4ActionPerformed
        // TODO add your handling code here:
        if(coffee[3].getQuantity(1)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Grande Caramel Latte?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c4.setEnabled(false);
                btn_buygrande_c4.setEnabled(false);
                this.client_order_list[7]++;
                this.refreshReceipt();
                coffee[3].setQuantity(1,
                        coffee[3].getQuantity(1) - this.client_order_list[7]);
            }
        }
        btn_buytall_c4.setEnabled(false);
        btn_buygrande_c4.setEnabled(false);
    }//GEN-LAST:event_btn_buygrande_c4ActionPerformed

    private void btn_buytall_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buytall_c5ActionPerformed
        // TODO add your handling code here:
        if(coffee[4].getQuantity(0)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Tall Cafè Mocha?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c5.setEnabled(false);
                btn_buygrande_c5.setEnabled(false);
                this.client_order_list[8]++;
                this.refreshReceipt();
                coffee[4].setQuantity(0,
                        coffee[4].getQuantity(0) - this.client_order_list[8]);
            }
        }
        btn_buytall_c5.setEnabled(false);
        btn_buygrande_c5.setEnabled(false);
    }//GEN-LAST:event_btn_buytall_c5ActionPerformed

    private void btn_buygrande_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buygrande_c5ActionPerformed
        // TODO add your handling code here:
        if(coffee[4].getQuantity(1)!=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Order Grande Cafè Mocha?", "Confirm order",
                    JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                btn_buytall_c5.setEnabled(false);
                btn_buygrande_c5.setEnabled(false);
                this.client_order_list[9]++;
                this.refreshReceipt();
                coffee[4].setQuantity(1,
                        coffee[4].getQuantity(1) - this.client_order_list[9]);
            }
        }
        btn_buytall_c5.setEnabled(false);
        btn_buygrande_c5.setEnabled(false);
    }//GEN-LAST:event_btn_buygrande_c5ActionPerformed

    private void btn_client_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_client_confirmActionPerformed
        // TODO add your handling code here:
        boolean empty_order = true;
        for(int order : this.client_order_list){
            if(order!=0){
                empty_order= false;
            }
        }
        if(!empty_order){
            Date now = new Date();
            String orderReceipt = "OFFICIAL RECEIPT\nCoffee Project\r\n"
                    + now
                    + "\r\nOrder:\r\nQty   Item                                        Price\r\n";
            for(int i=0; i<this.client_order_list.length; i++){
                if(this.client_order_list[i] > 0){
                    orderReceipt += this.client_order_list[i] + "    ";
                    orderReceipt += this.returnOrderString(i) + "           ";
                    orderReceipt += this.returnOrderPrice(i) * this.client_order_list[i] + "\r\n";
                }
            }
            int dialogResult = JOptionPane.showConfirmDialog(null, orderReceipt,
                    "Confirm order", JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION){
                for(int i=0; i<tbl_client_receipt.getRowCount(); i++){
                    for(int j=0; j<tbl_client_receipt.getColumnCount(); j++){
                        tbl_client_receipt.setValueAt(null, i, j);
                    }
                }
                for(int i=0; i<this.client_order_list.length; i++){
                    this.client_order_list[i] = 0;
                }
                try{
                    WriteFile data = new WriteFile(receipt_log_path, true);
                    data.writeToFile(orderReceipt);
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error:\n" + e);
                }
            }
            for(int i=0; i<coffee.length; i++){
                String overwrite = this.coffee[i].getQuantity(0) + "\r\n" +
                        this.coffee[i].getQuantity(1) + "\r\n" +
                        this.coffee[i].getPrice(0) + "\r\n" +
                        this.coffee[i].getPrice(1) + "\r\n" +
                        this.coffee[i].getImgPath();
                try{
                   WriteFile data = new WriteFile(this.data_reference[i]);
                   data.writeToFile(overwrite);
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error:\n" + e);
                }
            }
        }
    }//GEN-LAST:event_btn_client_confirmActionPerformed

    private void btn_client_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_client_cancelActionPerformed
        // TODO add your handling code here:
        this.coffee[0].setQuantity(0, this.coffee[0].getQuantity(0) + this.client_order_list[0]);
        this.coffee[0].setQuantity(1, this.coffee[0].getQuantity(1) + this.client_order_list[1]);
        this.coffee[1].setQuantity(0, this.coffee[1].getQuantity(0) + this.client_order_list[2]);
        this.coffee[1].setQuantity(1, this.coffee[1].getQuantity(1) + this.client_order_list[3]);
        this.coffee[2].setQuantity(0, this.coffee[2].getQuantity(0) + this.client_order_list[4]);
        this.coffee[2].setQuantity(1, this.coffee[2].getQuantity(1) + this.client_order_list[5]);
        this.coffee[3].setQuantity(0, this.coffee[3].getQuantity(0) + this.client_order_list[6]);
        this.coffee[3].setQuantity(1, this.coffee[3].getQuantity(1) + this.client_order_list[7]);
        this.coffee[4].setQuantity(0, this.coffee[4].getQuantity(0) + this.client_order_list[8]);
        this.coffee[4].setQuantity(1, this.coffee[4].getQuantity(1) + this.client_order_list[9]);        
        for(int i=0; i<this.client_order_list.length; i++){
            this.client_order_list[i] = 0;
        }
        for(int i=0; i<tbl_client_receipt.getRowCount(); i++){
            for(int j=0; j<tbl_client_receipt.getColumnCount(); j++){
                tbl_client_receipt.setValueAt(null, i, j);
            }
        }
    }//GEN-LAST:event_btn_client_cancelActionPerformed

    private void btn_adminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminLoginActionPerformed
        // TODO add your handling code here:
        String entered_string = JOptionPane.showInputDialog(this, "Enter Password");
        if(entered_string!=null){
            for(Cashier user : admin){
                if(entered_string.equals(user.getPassword())){
                    JOptionPane.showMessageDialog(this, "Logged in as " + user.getName());
                    pnl_main.removeAll();
                    pnl_main.add(pnl_admin);
                    pnl_main.repaint();
                    pnl_main.revalidate();
                    this.currentUser = user;
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Incorrect Password");
        }
    }//GEN-LAST:event_btn_adminLoginActionPerformed

    private void btn_admin_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_logoutActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you wish to logout?",
                    "Confirm logout", JOptionPane.YES_NO_OPTION);
        if(dialogResult==JOptionPane.YES_OPTION){
            pnl_main.removeAll();
            pnl_main.add(pnl_client);
            pnl_main.repaint();
            pnl_main.revalidate();
        }
    }//GEN-LAST:event_btn_admin_logoutActionPerformed

    private void btn_admin_pwdChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_pwdChangeActionPerformed
        // TODO add your handling code here:
        pwd_old.setEditable(true);
        pwd_new.setEditable(true);
        pwd_confirm.setEditable(true);
        btn_admin_confirmPwd.setEnabled(true);
    }//GEN-LAST:event_btn_admin_pwdChangeActionPerformed

    private void btn_admin_confirmPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_confirmPwdActionPerformed
        // TODO add your handling code here
        if(!pwd_old.getText().equals("") || !pwd_new.getText().equals("") || !pwd_confirm.getText().equals("")){
            if(pwd_old.getText().equals(currentUser.getPassword())){
                if(pwd_new.getText().equals(pwd_confirm.getText())){
                    currentUser.setPassword(pwd_confirm.getText());
                    currentUser.updateCredentials();
                    JOptionPane.showMessageDialog(this, "Password successfully changed");
                }else{
                    JOptionPane.showMessageDialog(this, "Passwords does not match");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Old password does not match");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Empty fields");
        }
        pwd_old.setEditable(false);
        pwd_new.setEditable(false);
        pwd_confirm.setEditable(false);
        btn_admin_confirmPwd.setEnabled(false);
        pwd_old.setText(null);
        pwd_new.setText(null);
        pwd_confirm.setText(null);
    }//GEN-LAST:event_btn_admin_confirmPwdActionPerformed
    private void refreshReceipt(){
        int table_row = 0;
        for(int i=0; i<this.client_order_list.length; i++){
            if(this.client_order_list[i]>0){
                tbl_client_receipt.setValueAt(this.client_order_list[i], table_row, 0);
                tbl_client_receipt.setValueAt(this.returnOrderString(i), table_row, 1);
                tbl_client_receipt.setValueAt(this.returnOrderPrice(i) * this.client_order_list[i], table_row, 2);
                table_row++;
            }
        }
    }
    
    private String returnOrderString(int order){
        switch(order){
            case 0:
                return "Tall Cafè Americano";
            case 1:
                return "Grande Cafè Americano";
            case 2:
                return "Tall Cappuccino";
            case 3:
                return "Grande Cappuccino";
            case 4:
                return "Tall Cafè Latte";
            case 5:
                return "Grande Cafè Latte";
            case 6:
                return "Tall Caramel Latte";
            case 7:
                return "Grande Caramel Latte";
            case 8:
                return "Tall Cafè Mocha";
            default:
                return "Grande Cafè Mocha";
        }
    }
    
    private int returnOrderPrice(int order){
        switch(order){
            case 0:
                return this.coffee[0].getPrice(0);
            case 1:
                return this.coffee[0].getPrice(1);
            case 2:
                return this.coffee[1].getPrice(0);
            case 3:
                return this.coffee[1].getPrice(1);
            case 4:
                return this.coffee[2].getPrice(0);
            case 5:
                return this.coffee[2].getPrice(1);
            case 6:
                return this.coffee[3].getPrice(0);
            case 7:
                return this.coffee[3].getPrice(1);
            case 8:
                return this.coffee[4].getPrice(0);
            default:
                return this.coffee[4].getPrice(1);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adminLogin;
    private javax.swing.JButton btn_admin_confirmPwd;
    private javax.swing.JButton btn_admin_logout;
    private javax.swing.JButton btn_admin_pwdChange;
    private javax.swing.JButton btn_buygrande_c1;
    private javax.swing.JButton btn_buygrande_c2;
    private javax.swing.JButton btn_buygrande_c3;
    private javax.swing.JButton btn_buygrande_c4;
    private javax.swing.JButton btn_buygrande_c5;
    private javax.swing.JButton btn_buygrande_f1;
    private javax.swing.JButton btn_buygrande_f2;
    private javax.swing.JButton btn_buygrande_f3;
    private javax.swing.JButton btn_buygrande_f4;
    private javax.swing.JButton btn_buygrande_f5;
    private javax.swing.JButton btn_buyproject_f1;
    private javax.swing.JButton btn_buyproject_f2;
    private javax.swing.JButton btn_buyproject_f3;
    private javax.swing.JButton btn_buyproject_f4;
    private javax.swing.JButton btn_buyproject_f5;
    private javax.swing.JButton btn_buytall_c1;
    private javax.swing.JButton btn_buytall_c2;
    private javax.swing.JButton btn_buytall_c3;
    private javax.swing.JButton btn_buytall_c4;
    private javax.swing.JButton btn_buytall_c5;
    private javax.swing.JButton btn_client_cancel;
    private javax.swing.JButton btn_client_confirm;
    private javax.swing.JButton btn_sel_c1;
    private javax.swing.JButton btn_sel_c2;
    private javax.swing.JButton btn_sel_c3;
    private javax.swing.JButton btn_sel_c4;
    private javax.swing.JButton btn_sel_c5;
    private javax.swing.JButton btn_sel_f1;
    private javax.swing.JButton btn_sel_f2;
    private javax.swing.JButton btn_sel_f3;
    private javax.swing.JButton btn_sel_f4;
    private javax.swing.JButton btn_sel_f5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_client_img;
    private javax.swing.JPanel pnl_admin;
    private javax.swing.JPanel pnl_admin_main;
    private javax.swing.JPanel pnl_client;
    private javax.swing.JPanel pnl_client_coffee;
    private javax.swing.JPanel pnl_client_frappe;
    private javax.swing.JPanel pnl_client_receipt;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPasswordField pwd_confirm;
    private javax.swing.JPasswordField pwd_new;
    private javax.swing.JPasswordField pwd_old;
    private javax.swing.JTable tbl_client_receipt;
    // End of variables declaration//GEN-END:variables
}
